# Generated by Django 5.1.7 on 2025-06-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
