# Generated by Django 5.1.7 on 2025-06-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadomaquina',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
