# Generated by Django 5.1.7 on 2025-06-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='unidades',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
