# Generated by Django 5.1.7 on 2025-06-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_pedido_costo_total_pedido_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
