# Generated by Django 5.1.7 on 2025-06-22 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_pedido_costo_total_alter_pedido_costo_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('propietario', 'Propietario'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
        migrations.CreateModel(
            name='Granja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
