# Generated by Django 5.1.7 on 2025-06-22 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_customuser_rol_granja'),
    ]

    operations = [
        migrations.AddField(
            model_name='huevo',
            name='granja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.granja'),
        ),
    ]
