# Generated by Django 5.1.7 on 2025-06-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_huevo_granja'),
    ]

    operations = [
        migrations.AddField(
            model_name='huevo',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
