# Generated by Django 5.1.7 on 2025-06-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_huevo_vendido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='granja',
        ),
    ]
