# Generated by Django 5.1.7 on 2025-06-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_remove_pedido_granja'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioMaple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=5, unique=True)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
